apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cstorvolumeattachments.cstor.openebs.io
spec:
  group: cstor.openebs.io
  version: v1
  scope: Namespaced
  names:
    plural: cstorvolumeattachments
    singular: cstorvolumeattachment
    kind: CStorVolumeAttachment
    shortNames:
    - cstorvolumeattachment
    - cva